# Generated by Django 4.1.7 on 2023-03-05 22:21

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Страница "О нас"',
                'verbose_name_plural': 'Страницы "О нас"',
            },
        ),
    ]
